# Generated by Django 4.2.11 on 2025-05-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='excel_file',
            field=models.FileField(upload_to=''),
        ),
    ]
