# Generated by Django 4.2.11 on 2025-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aoptarget_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoptarget',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='position',
            field=models.CharField(choices=[('DM', 'District Manager'), ('AM', 'Area Manager'), ('Seller', 'Seller')], max_length=6),
        ),
    ]
