# Generated by Django 4.2.11 on 2025-05-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employeedata_excel_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedata',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='employeedata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
